#!/bin/bash
#PBS -P CBBI1154
#PBS -N R1Production
#PBS -l select=1:ncpus=6:ngpus=1
#PBS -l walltime=1:00:00
#PBS -q gpu_1
#PBS -m abe
#PBS -M lzondagh@uwc.ac.za
#PBS -o /mnt/lustre/users/lzondagh/BACE_1/MD_simulations/LIG/production/19_production_MD_r1_output
#PBS -e /mnt/lustre/users/lzondagh/BACE_1/MD_simulations/LIG/production/19_production_MD_r1_error
#PBS

module purge
module add chpc/amber/20/cuda11.2/mpich-3.4.1/gcc-6.1.0
source $AMBERHOME/amber.sh

pushd /mnt/lustre/users/lzondagh/BACE_1/MD_simulations/LIG/production
exe=$AMBERHOME/bin/pmemd.cuda

$exe -O -i 19_production_MD.in -o 19_production_MD_r1.out -p ../complex_solvated.parm7 -c ../preproduction/18_no_restrnts_MD.rst7 -r 19_production_MD_r1.rst7 -ref ../preproduction/18_no_restrnts_MD.rst7 -inf ../MD_info/19_production_MD_run_1.info -x 19_production_MD_trj_r1.nc

popd
